# Diet and Health Analysis Project

## Notebook 1: Data Cleaning

### Cleaned all the datasets

In [1]:
import pandas as pd
import numpy as np

In [2]:
food = pd.read_csv(
    r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\raw\food_consumption.csv",
    header=1)
gdp = pd.read_csv(
    r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\raw\gdp.csv",
    skiprows=4)
life = pd.read_csv(
    r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\raw\life_expectancy.csv",
    skiprows=4)
diabetes = pd.read_csv(
    r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\raw\diabetes.csv",
    skiprows=4)
obesity = pd.read_csv(
    r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\raw\obesity.csv")

In [3]:
food.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unit,Value
0,Afghanistan,Food supply quantity (kg/capita/yr),Eggs,kg/cap,0.58
1,Afghanistan,Food supply quantity (kg/capita/yr),"Fish, Seafood",kg/cap,0.38
2,Afghanistan,Food supply quantity (kg/capita/yr),Fruits - Excluding Wine,kg/cap,39.92
3,Afghanistan,Food supply quantity (kg/capita/yr),Meat,kg/cap,6.39
4,Afghanistan,Food supply quantity (kg/capita/yr),Milk - Excluding Butter,kg/cap,37.11

In [4]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1241 entries, 0 to 1240
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1239 non-null   object
 1   Unnamed: 1  1239 non-null   object
 2   Unnamed: 2  1239 non-null   object
 3   Unit        1239 non-null   object
 4   Value       1239 non-null   float64
dtypes: float64(1), object(4)
memory usage: 48.6+ KB

In [6]:
food.shape

(1241, 5)

In [8]:
food.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unit', 'Value'], dtype='object')

In [9]:
food.columns = ["Country", "Element", "Food_Category", "Unit", "Value"]

In [10]:
food.head()

,Country,Element,Food_Category,Unit,Value
0,Afghanistan,Food supply quantity (kg/capita/yr),Eggs,kg/cap,0.58
1,Afghanistan,Food supply quantity (kg/capita/yr),"Fish, Seafood",kg/cap,0.38
2,Afghanistan,Food supply quantity (kg/capita/yr),Fruits - Excluding Wine,kg/cap,39.92
3,Afghanistan,Food supply quantity (kg/capita/yr),Meat,kg/cap,6.39
4,Afghanistan,Food supply quantity (kg/capita/yr),Milk - Excluding Butter,kg/cap,37.11

In [11]:
food.isnull().sum()

Country          2
Element          2
Food_Category    2
Unit             2
Value            2
dtype: int64

In [12]:
food[food.isnull().any(axis=1)]

     Country Element Food_Category Unit  Value
1239     NaN     NaN           NaN  NaN    NaN
1240     NaN     NaN           NaN  NaN    NaN

In [13]:
food = food.dropna(how="all")

In [14]:
food.shape

(1239, 5)

In [15]:
food.isnull().sum()

Country          0
Element          0
Food_Category    0
Unit             0
Value            0
dtype: int64

In [39]:
food.duplicated().sum()

0

In [16]:
food.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\food_clean.csv", index=False)

In [17]:
gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,28440.041688,30082.158423,30645.890602,22759.807175,26749.329609,30975.998912,35718.753119,39498.594129,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN,NaN

In [18]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            156 non-null    float64
 7   1963            156 non-null    float64
 8   1964            156 non-null    float64
 9   1965            162 non-null    float64
 10  1966            163 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            260 non-null    float64
 60  2016            259 non-null    float64
 61  2017            259 non-null    float64
 62  2018            259 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            257 non-null    float64
 67  2023            251 non-null    float64
 68  2024            240 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [19]:
gdp.shape

(266, 71)

In [20]:
gdp.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

In [21]:
gdp_clean = gdp[["Country Name", "Country Code", "2023"]]

In [22]:
gdp_clean.columns = ["Country", "Country_Code", "GDP_per_Capita"]

In [23]:
gdp_clean.head()

                       Country Country_Code  GDP_per_Capita
0                        Aruba          ABW    35718.753119
1  Africa Eastern and Southern          AFE     1571.449189
2                  Afghanistan          AFG      413.757895
3   Africa Western and Central          AFW     1841.855064
4                       Angola          AGO     2916.136633

In [24]:
gdp_clean.isnull().sum()

Country            0
Country_Code       0
GDP_per_Capita    15
dtype: int64

In [40]:
gdp_clean[gdp_clean.isnull().any(axis=1)]

                       Country Country_Code  GDP_per_Capita
11              American Samoa          ASM             NaN
50                        Cuba          CUB             NaN
69                     Eritrea          ERI             NaN
84                   Gibraltar          GIB             NaN
93                        Guam          GUM             NaN
108                Isle of Man          IMN             NaN
110             Not classified          INX             NaN
147   St. Martin (French part)          MAF             NaN
164   Northern Mariana Islands          MNP             NaN
193  Korea, Dem. People's Rep.          PRK             NaN
216                South Sudan          SSD             NaN
227       Syrian Arab Republic          SYR             NaN
255     British Virgin Islands          VGB             NaN
256      Virgin Islands (U.S.)          VIR             NaN
262                Yemen, Rep.          YEM             NaN

In [38]:
gdp_clean.duplicated().sum()

0

In [25]:
gdp_clean.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\gdp_clean.csv", index=False)

In [27]:
life.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,64.049000,64.215000,64.602000,64.944000,65.303000,65.615000,...,75.620000,75.880000,76.019000,75.406000,73.655000,76.226000,76.353000,76.500000,NaN,NaN
1,Africa Eastern and Southern,AFE,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,44.169658,44.468838,44.877890,45.160583,45.535695,45.770723,...,62.591275,63.330691,63.857261,63.766484,62.979999,64.487152,65.146228,65.349930,NaN,NaN
2,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,32.799000,33.291000,33.757000,34.201000,34.673000,35.124000,...,62.406000,62.443000,62.941000,61.454000,60.417000,65.617000,66.035000,66.289000,NaN,NaN
3,Africa Western and Central,AFW,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.779636,38.058973,38.681792,38.936918,39.194580,39.479784,...,56.626622,57.037104,57.149956,57.364736,57.362736,57.987850,58.855740,59.049811,NaN,NaN
4,Angola,AGO,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,37.933000,36.902000,37.168000,37.419000,37.704000,37.968000,...,62.122000,62.622000,63.051000,63.116000,62.958000,64.246000,64.617000,64.805000,NaN,NaN

In [28]:
life.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            263 non-null    float64
 5   1961            264 non-null    float64
 6   1962            264 non-null    float64
 7   1963            263 non-null    float64
 8   1964            263 non-null    float64
 9   1965            263 non-null    float64
 10  1966            264 non-null    float64
 11  1967            264 non-null    float64
 12  1968            264 non-null    float64
 13  1969            264 non-null    float64
 14  1970            264 non-null    float64
 15  1971            264 non-null    float64
 16  1972            264 non-null    float64
 17  1973            264 non-null    float64
 18  1974            264 non-null    float64
 19  1975            264 non-null    float64
 20  1976            264 non-null    float64
 21  1977            264 non-null    float64
 22  1978            264 non-null    float64
 23  1979            264 non-null    float64
 24  1980            264 non-null    float64
 25  1981            264 non-null    float64
 26  1982            264 non-null    float64
 27  1983            264 non-null    float64
 28  1984            264 non-null    float64
 29  1985            264 non-null    float64
 30  1986            264 non-null    float64
 31  1987            264 non-null    float64
 32  1988            264 non-null    float64
 33  1989            264 non-null    float64
 34  1990            265 non-null    float64
 35  1991            265 non-null    float64
 36  1992            265 non-null    float64
 37  1993            265 non-null    float64
 38  1994            265 non-null    float64
 39  1995            265 non-null    float64
 40  1996            265 non-null    float64
 41  1997            265 non-null    float64
 42  1998            265 non-null    float64
 43  1999            265 non-null    float64
 44  2000            265 non-null    float64
 45  2001            265 non-null    float64
 46  2002            265 non-null    float64
 47  2003            265 non-null    float64
 48  2004            265 non-null    float64
 49  2005            265 non-null    float64
 50  2006            265 non-null    float64
 51  2007            265 non-null    float64
 52  2008            265 non-null    float64
 53  2009            265 non-null    float64
 54  2010            265 non-null    float64
 55  2011            265 non-null    float64
 56  2012            265 non-null    float64
 57  2013            265 non-null    float64
 58  2014            265 non-null    float64
 59  2015            265 non-null    float64
 60  2016            265 non-null    float64
 61  2017            265 non-null    float64
 62  2018            265 non-null    float64
 63  2019            265 non-null    float64
 64  2020            265 non-null    float64
 65  2021            265 non-null    float64
 66  2022            265 non-null    float64
 67  2023            265 non-null    float64
 68  2024            265 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [29]:
life.shape

(266, 71)

In [31]:
life.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

In [32]:
life_clean = life[["Country Name", "Country Code", "2023"]]

In [33]:
life_clean.columns = ["Country", "Country_Code", "Life_Expectancy"]

In [34]:
life_clean.head()

                       Country Country_Code  Life_Expectancy
0                        Aruba          ABW        76.353000
1  Africa Eastern and Southern          AFE        65.146228
2                  Afghanistan          AFG        66.035000
3   Africa Western and Central          AFW        58.855740
4                       Angola          AGO        64.617000

In [35]:
life_clean.isnull().sum()

Country            0
Country_Code       0
Life_Expectancy    1
dtype: int64

In [41]:
life_clean[life_clean.isnull().any(axis=1)]

            Country Country_Code  Life_Expectancy
110  Not classified          INX              NaN

In [42]:
life_clean = life_clean.dropna(subset=["Life_Expectancy"])

In [43]:
life_clean.duplicated().sum()

0

In [44]:
life_clean.isnull().sum()

Country            0
Country_Code       0
Life_Expectancy    0
dtype: int64

In [47]:
life_clean.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\life_expectancy_clean.csv", index=False)

In [48]:
diabetes.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.600000,NaN,NaN
1,Africa Eastern and Southern,AFE,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.454044,NaN,NaN
2,Afghanistan,AFG,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.700000,NaN,NaN
3,Africa Western and Central,AFW,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.219277,NaN,NaN
4,Angola,AGO,Diabetes prevalence (% of population ages 20 t...,SH.STA.DIAB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.900000,NaN,NaN

In [49]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 71 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    object
 1   Country Code    266 non-null    object
 2   Indicator Name  266 non-null    object
 3   Indicator Code  266 non-null    object
 4   1960            0 non-null      float64
 5   1961            0 non-null      float64
 6   1962            0 non-null      float64
 7   1963            0 non-null      float64
 8   1964            0 non-null      float64
 9   1965            0 non-null      float64
 10  1966            0 non-null      float64
 11  1967            0 non-null      float64
 12  1968            0 non-null      float64
 13  1969            0 non-null      float64
 14  1970            0 non-null      float64
 15  1971            0 non-null      float64
 16  1972            0 non-null      float64
 17  1973            0 non-null      float64
 18  1974            0 non-null      float64
 19  1975            0 non-null      float64
 20  1976            0 non-null      float64
 21  1977            0 non-null      float64
 22  1978            0 non-null      float64
 23  1979            0 non-null      float64
 24  1980            0 non-null      float64
 25  1981            0 non-null      float64
 26  1982            0 non-null      float64
 27  1983            0 non-null      float64
 28  1984            0 non-null      float64
 29  1985            0 non-null      float64
 30  1986            0 non-null      float64
 31  1987            0 non-null      float64
 32  1988            0 non-null      float64
 33  1989            0 non-null      float64
 34  1990            0 non-null      float64
 35  1991            0 non-null      float64
 36  1992            0 non-null      float64
 37  1993            0 non-null      float64
 38  1994            0 non-null      float64
 39  1995            0 non-null      float64
 40  1996            0 non-null      float64
 41  1997            0 non-null      float64
 42  1998            0 non-null      float64
 43  1999            0 non-null      float64
 44  2000            17 non-null     float64
 45  2001            0 non-null      float64
 46  2002            0 non-null      float64
 47  2003            0 non-null      float64
 48  2004            0 non-null      float64
 49  2005            0 non-null      float64
 50  2006            0 non-null      float64
 51  2007            0 non-null      float64
 52  2008            0 non-null      float64
 53  2009            0 non-null      float64
 54  2010            0 non-null      float64
 55  2011            251 non-null    float64
 56  2012            0 non-null      float64
 57  2013            0 non-null      float64
 58  2014            0 non-null      float64
 59  2015            0 non-null      float64
 60  2016            0 non-null      float64
 61  2017            0 non-null      float64
 62  2018            0 non-null      float64
 63  2019            0 non-null      float64
 64  2020            0 non-null      float64
 65  2021            0 non-null      float64
 66  2022            0 non-null      float64
 67  2023            0 non-null      float64
 68  2024            257 non-null    float64
 69  2025            0 non-null      float64
 70  Unnamed: 70     0 non-null      float64
dtypes: float64(67), object(4)
memory usage: 147.7+ KB

In [50]:
diabetes.shape

(266, 71)

In [51]:
diabetes.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025', 'Unnamed: 70'],
      dtype='object')

In [52]:
diabetes_clean = diabetes[["Country Name", "Country Code", "2024"]]

In [53]:
diabetes_clean.columns = ["Country", "Country_Code", "Diabetes_Prevalence"]

In [54]:
diabetes_clean.head()

                       Country Country_Code  Diabetes_Prevalence
0                        Aruba          ABW             4.600000
1  Africa Eastern and Southern          AFE             6.454044
2                  Afghanistan          AFG            11.700000
3   Africa Western and Central          AFW             4.219277
4                       Angola          AGO             4.900000

In [55]:
diabetes_clean.isnull().sum()

Country                0
Country_Code           0
Diabetes_Prevalence    9
dtype: int64

In [56]:
diabetes_clean[diabetes_clean.isnull().any(axis=1)]

                       Country Country_Code  Diabetes_Prevalence
11              American Samoa          ASM                  NaN
38             Channel Islands          CHI                  NaN
84                   Gibraltar          GIB                  NaN
110             Not classified          INX                  NaN
147   St. Martin (French part)          MAF                  NaN
164   Northern Mariana Islands          MNP                  NaN
225  Sint Maarten (Dutch part)          SXM                  NaN
228   Turks and Caicos Islands          TCA                  NaN
255     British Virgin Islands          VGB                  NaN

In [57]:
diabetes_clean.duplicated().sum()

0

In [58]:
diabetes_clean = diabetes_clean.dropna(subset=["Diabetes_Prevalence"])

In [59]:
diabetes_clean.isnull().sum()

Country                0
Country_Code           0
Diabetes_Prevalence    0
dtype: int64

In [60]:
diabetes_clean.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\diabetes_clean.csv", index=False)

In [61]:
obesity.head()

,Entity,Code,Year,"Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+ years of age"
0,Afghanistan,AFG,2023,17.805538
1,Albania,ALB,2023,26.458910
2,Algeria,DZA,2023,23.822920
3,Andorra,AND,2023,19.466227
4,Angola,AGO,2023,11.380967

In [62]:
obesity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 4 columns):
 #   Column                                                                                                       Non-Null Count  Dtype
---  ------                                                                                                       --------------  -----
 0   Entity                                                                                                       193 non-null    object
 1   Code                                                                                                         193 non-null    object
 2   Year                                                                                                         193 non-null    int64
 3   Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age  193 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 6.2+ KB

In [63]:
obesity.shape

(193, 4)

In [64]:
obesity.columns

Index(['Entity', 'Code', 'Year',
       'Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age'],
      dtype='object')

In [66]:
obesity.isnull().sum()

Entity                                                                                                         0
Code                                                                                                           0
Year                                                                                                           0
Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age    0
dtype: int64

In [68]:
obesity_clean = obesity.rename(columns={"Entity": "Country", "Code": "Country_Code", "Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+ years of age": "Obesity"})

In [69]:
obesity_clean = obesity_clean.drop(columns=["Year"])

In [70]:
obesity_clean.head()

,Country,Country_Code,"Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+ years of age"
0,Afghanistan,AFG,17.805538
1,Albania,ALB,26.458910
2,Algeria,DZA,23.822920
3,Andorra,AND,19.466227
4,Angola,AGO,11.380967

In [71]:
obesity_clean.isnull().sum()

Country                                                                                                        0
Country_Code                                                                                                   0
Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age    0
dtype: int64

In [72]:
obesity_clean.duplicated().sum()

0

In [73]:
obesity_clean.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\obesity_clean.csv", index=False)