# Diet and Health Analysis Project

## Notebook 2: Data Merging

### Merged all the cleaned dataset into one for analysis

In [1]:
import pandas as pd

In [2]:
food = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\food_clean.csv")

gdp = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\gdp_clean.csv")

life = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\life_expectancy_clean.csv")

diabetes = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\diabetes_clean.csv")

obesity = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\obesity_clean.csv")

In [3]:
food.shape

(1239, 5)

In [4]:
gdp.shape

(266, 3)

In [5]:
life.shape

(265, 3)

In [6]:
diabetes.shape

(257, 3)

In [7]:
obesity.shape

(193, 3)

In [8]:
food.head(10)

,Country,Element,Food_Category,Unit,Value
0,Afghanistan,Food supply quantity (kg/capita/yr),Eggs,kg/cap,0.58
1,Afghanistan,Food supply quantity (kg/capita/yr),"Fish, Seafood",kg/cap,0.38
2,Afghanistan,Food supply quantity (kg/capita/yr),Fruits - Excluding Wine,kg/cap,39.92
3,Afghanistan,Food supply quantity (kg/capita/yr),Meat,kg/cap,6.39
4,Afghanistan,Food supply quantity (kg/capita/yr),Milk - Excluding Butter,kg/cap,37.11
5,Afghanistan,Food supply quantity (kg/capita/yr),Sugar & Sweeteners,kg/cap,10.60
6,Afghanistan,Food supply quantity (kg/capita/yr),Vegetables,kg/cap,63.41
7,Albania,Food supply quantity (kg/capita/yr),Eggs,kg/cap,11.62
8,Albania,Food supply quantity (kg/capita/yr),"Fish, Seafood",kg/cap,8.60
9,Albania,Food supply quantity (kg/capita/yr),Fruits - Excluding Wine,kg/cap,185.68

In [9]:
food["Food_Category"].unique()

array(['Eggs', 'Fish, Seafood', 'Fruits - Excluding Wine', 'Meat',
       'Milk - Excluding Butter', 'Sugar & Sweeteners', 'Vegetables'],
      dtype=object)

In [10]:
food["Food_Category"].nunique()

7

In [11]:
food_pivot = food.pivot(index="Country", columns="Food_Category", values="Value").reset_index()

In [12]:
food_pivot.head()

Food_Category,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09

In [13]:
food_pivot.columns.name = None

In [14]:
food_pivot.head()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09

In [15]:
food_pivot.shape

(177, 8)

In [16]:
food_pivot.isnull().sum()

Country                    0
Eggs                       0
Fish, Seafood              0
Fruits - Excluding Wine    0
Meat                       0
Milk - Excluding Butter    0
Sugar & Sweeteners         0
Vegetables                 0
dtype: int64

In [17]:
food_pivot.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\food_pivot.csv", index=False)

In [18]:
food.columns

Index(['Country', 'Element', 'Food_Category', 'Unit', 'Value'], dtype='object')

In [19]:
gdp.columns

Index(['Country', 'Country_Code', 'GDP_per_Capita'], dtype='object')

In [20]:
life.columns

Index(['Country', 'Country_Code', 'Life_Expectancy'], dtype='object')

In [21]:
diabetes.columns

Index(['Country', 'Country_Code', 'Diabetes_Prevalence'], dtype='object')

In [22]:
obesity.columns

Index(['Country', 'Country_Code',
       'Obesity among adults, BMI >= 30 kg/m2 (crude estimate) (%) - Sex: both sexes - Age group: 18+  years of age'],
      dtype='object')

In [23]:
merged = pd.merge(food_pivot, gdp, on="Country", how="left")

In [24]:
merged.head()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables,Country_Code,GDP_per_Capita
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41,AFG,413.757895
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37,ALB,9730.869219
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33,DZA,5370.477235
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87,AGO,2916.136633
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09,ATG,21494.547400

In [25]:
merged = pd.merge(merged, life[["Country", "Life_Expectancy"]], on="Country", how="left")

In [26]:
merged = pd.merge(merged, diabetes[["Country", "Diabetes_Prevalence"]], on="Country", how="left")

In [27]:
merged.head()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables,Country_Code,GDP_per_Capita,Life_Expectancy,Diabetes_Prevalence
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41,AFG,413.757895,66.035,11.7
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37,ALB,9730.869219,79.602,10.6
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33,DZA,5370.477235,76.261,17.5
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87,AGO,2916.136633,64.617,4.9
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09,ATG,21494.547400,77.598,11.6

In [28]:
obesity.columns = ["Country", "Country_Code", "Obesity"]

In [29]:
obesity.columns

Index(['Country', 'Country_Code', 'Obesity'], dtype='object')

In [30]:
merged = pd.merge(merged, obesity[["Country", "Obesity"]], on="Country", how="left")

In [31]:
merged.head()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables,Country_Code,GDP_per_Capita,Life_Expectancy,Diabetes_Prevalence,Obesity
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41,AFG,413.757895,66.035,11.7,17.805538
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37,ALB,9730.869219,79.602,10.6,26.458910
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33,DZA,5370.477235,76.261,17.5,23.822920
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87,AGO,2916.136633,64.617,4.9,11.380967
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09,ATG,21494.547400,77.598,11.6,34.713180

In [32]:
merged.tail()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables,Country_Code,GDP_per_Capita,Life_Expectancy,Diabetes_Prevalence,Obesity
172,Venezuela (Bolivarian Republic of),6.94,8.75,91.82,37.98,124.63,35.26,47.94,NaN,NaN,NaN,NaN,NaN
173,Viet Nam,3.96,40.06,99.61,60.48,37.38,29.60,191.32,VNM,4323.350320,74.588,3.4,NaN
174,Yemen,1.60,2.02,26.47,13.72,32.80,25.08,19.85,NaN,NaN,NaN,NaN,11.206609
175,Zambia,2.70,12.89,4.27,17.63,8.10,10.69,17.95,ZMB,1330.727806,66.349,10.3,9.585259
176,Zimbabwe,1.56,2.63,43.01,57.58,27.22,27.60,134.34,ZWE,2195.224921,62.775,1.5,12.747547

In [33]:
merged.shape

(177, 13)

In [38]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Country                  177 non-null    object
 1   Eggs                     177 non-null    float64
 2   Fish, Seafood            177 non-null    float64
 3   Fruits - Excluding Wine  177 non-null    float64
 4   Meat                     177 non-null    float64
 5   Milk - Excluding Butter  177 non-null    float64
 6   Sugar & Sweeteners       177 non-null    float64
 7   Vegetables               177 non-null    float64
 8   Country_Code             149 non-null    object
 9   GDP_per_Capita           148 non-null    float64
 10  Life_Expectancy          149 non-null    float64
 11  Diabetes_Prevalence      149 non-null    float64
 12  Obesity                  152 non-null    float64
dtypes: float64(11), object(2)
memory usage: 18.1+ KB

In [34]:
merged.isnull().sum()

Country                     0
Eggs                        0
Fish, Seafood               0
Fruits - Excluding Wine     0
Meat                        0
Milk - Excluding Butter     0
Sugar & Sweeteners          0
Vegetables                  0
Country_Code               28
GDP_per_Capita             29
Life_Expectancy            28
Diabetes_Prevalence        28
Obesity                    25
dtype: int64

In [35]:
merged.duplicated().sum()

0

In [36]:
merged[merged["GDP_per_Capita"].isnull()]["Country"]

10                                               Bahamas
18                      Bolivia (Plurinational State of)
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
36                                                 Congo
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
47                                                 Egypt
57                                                Gambia
73                            Iran (Islamic Republic of)
84                                            Kyrgyzstan
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
129                                    Republic of Korea
130                                  Republic of Moldova
134                                Saint Kitts and Nevis
135                                          Saint Lucia
136                     Saint Vincent and the Grenadines
144                                             Slovakia
153                                 Syrian Arab Republic
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
174                                                Yemen
Name: Country, dtype: object

In [37]:
merged[merged["Life_Expectancy"].isnull()]["Country"]

10                                               Bahamas
18                      Bolivia (Plurinational State of)
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
36                                                 Congo
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
47                                                 Egypt
57                                                Gambia
73                            Iran (Islamic Republic of)
84                                            Kyrgyzstan
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
129                                    Republic of Korea
130                                  Republic of Moldova
134                                Saint Kitts and Nevis
135                                          Saint Lucia
136                     Saint Vincent and the Grenadines
144                                             Slovakia
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
174                                                Yemen
Name: Country, dtype: object

In [38]:
merged[merged["Diabetes_Prevalence"].isnull()]["Country"]

10                                               Bahamas
18                      Bolivia (Plurinational State of)
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
36                                                 Congo
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
47                                                 Egypt
57                                                Gambia
73                            Iran (Islamic Republic of)
84                                            Kyrgyzstan
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
129                                    Republic of Korea
130                                  Republic of Moldova
134                                Saint Kitts and Nevis
135                                          Saint Lucia
136                     Saint Vincent and the Grenadines
144                                             Slovakia
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
174                                                Yemen
Name: Country, dtype: object

In [39]:
merged[merged["Diabetes_Prevalence"].isnull()]["Country"]

10                                               Bahamas
18                      Bolivia (Plurinational State of)
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
36                                                 Congo
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
47                                                 Egypt
57                                                Gambia
73                            Iran (Islamic Republic of)
84                                            Kyrgyzstan
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
129                                    Republic of Korea
130                                  Republic of Moldova
134                                Saint Kitts and Nevis
135                                          Saint Lucia
136                     Saint Vincent and the Grenadines
144                                             Slovakia
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
174                                                Yemen
Name: Country, dtype: object

In [40]:
merged[merged["Obesity"].isnull()]["Country"]

18                      Bolivia (Plurinational State of)
24                                            Cabo Verde
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
55                                      French Polynesia
73                            Iran (Islamic Republic of)
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
112                                        New Caledonia
129                                    Republic of Korea
130                                  Republic of Moldova
132                                   Russian Federation
153                                 Syrian Arab Republic
156                                          Timor-Leste
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
173                                             Viet Nam
Name: Country, dtype: object

In [41]:
merged.shape

(177, 13)

In [42]:
merged.isnull().sum()

Country                     0
Eggs                        0
Fish, Seafood               0
Fruits - Excluding Wine     0
Meat                        0
Milk - Excluding Butter     0
Sugar & Sweeteners          0
Vegetables                  0
Country_Code               28
GDP_per_Capita             29
Life_Expectancy            28
Diabetes_Prevalence        28
Obesity                    25
dtype: int64

In [43]:
country_lookup = gdp[["Country", "Country_Code"]]

In [44]:
food_code = pd.merge(food_pivot, country_lookup, on="Country", how="left")

In [45]:
food_code.head()

,Country,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Vegetables,Country_Code
0,Afghanistan,0.58,0.38,39.92,6.39,37.11,10.60,63.41,AFG
1,Albania,11.62,8.60,185.68,56.68,290.98,53.65,382.37,ALB
2,Algeria,6.05,2.75,107.14,22.27,145.25,31.07,221.33,DZA
3,Angola,1.74,14.34,82.42,18.59,7.82,14.66,54.87,AGO
4,Antigua and Barbuda,6.02,54.52,241.73,96.37,117.21,47.98,101.09,ATG

In [46]:
food_code[food_code["Country_Code"].isnull()]["Country"]

10                                               Bahamas
18                      Bolivia (Plurinational State of)
30                                  China, Hong Kong SAR
31                                      China, Macao SAR
32                             China, Taiwan Province of
33                                       China, mainland
36                                                 Congo
41                                         Côte d'Ivoire
42                      Democratic Republic of the Congo
47                                                 Egypt
57                                                Gambia
73                            Iran (Islamic Republic of)
84                                            Kyrgyzstan
85                      Lao People's Democratic Republic
102                     Micronesia (Federated States of)
111                         Netherlands (Kingdom of the)
129                                    Republic of Korea
130                                  Republic of Moldova
134                                Saint Kitts and Nevis
135                                          Saint Lucia
136                     Saint Vincent and the Grenadines
144                                             Slovakia
162                                              Türkiye
166    United Kingdom of Great Britain and Northern I...
167                          United Republic of Tanzania
168                             United States of America
172                   Venezuela (Bolivarian Republic of)
174                                                Yemen
Name: Country, dtype: object

In [47]:
gdp[gdp["Country"].str.contains("Bah", case=False, na=False)]

         Country Country_Code  GDP_per_Capita
22       Bahrain          BHR    29290.128422
23  Bahamas, The          BHS    38231.774484

In [48]:
gdp[gdp["Country"].str.contains("Bolivia", case=False, na=False)]

    Country Country_Code  GDP_per_Capita
28  Bolivia          BOL     4274.708205

In [49]:
gdp[gdp["Country"].str.contains("Hong", case=False, na=False)]

                 Country Country_Code  GDP_per_Capita
96  Hong Kong SAR, China          HKG    50562.363314

In [50]:
gdp[gdp["Country"].str.contains("Macao", case=False, na=False)]

              Country Country_Code  GDP_per_Capita
146  Macao SAR, China          MAC    67216.363111

In [51]:
gdp[gdp["Country"].str.contains("Taiwan", case=False, na=False)]

Empty DataFrame
Columns: [Country, Country_Code, GDP_per_Capita]
Index: []

In [52]:
gdp[gdp["Country"].str.contains("Congo", case=False, na=False)]

             Country Country_Code  GDP_per_Capita
43  Congo, Dem. Rep.          COD      660.212052
44       Congo, Rep.          COG     2477.978455

In [53]:
gdp[gdp["Country"].str.contains("Egypt", case=False, na=False)]

             Country Country_Code  GDP_per_Capita
67  Egypt, Arab Rep.          EGY     3456.789685

In [54]:
gdp[gdp["Country"].str.contains("Iran", case=False, na=False)]

                Country Country_Code  GDP_per_Capita
112  Iran, Islamic Rep.          IRN     5049.299316

In [55]:
gdp[gdp["Country"].str.contains("Korea", case=False, na=False)]

                       Country Country_Code  GDP_per_Capita
126                Korea, Rep.          KOR    35674.095996
193  Korea, Dem. People's Rep.          PRK             NaN

In [56]:
gdp[gdp["Country"].str.contains("United", case=False, na=False)]

                  Country Country_Code  GDP_per_Capita
8    United Arab Emirates          ARE    49850.687218
81         United Kingdom          GBR    49944.470212
251         United States          USA    81032.262118

In [57]:
gdp[gdp["Country"].str.contains("Turkey", case=False, na=False)]

Empty DataFrame
Columns: [Country, Country_Code, GDP_per_Capita]
Index: []

In [58]:
gdp[gdp["Country"].str.contains("Vene", case=False, na=False)]

           Country Country_Code  GDP_per_Capita
254  Venezuela, RB          VEN     3617.435946

In [59]:
food_code = pd.merge(food_pivot, country_lookup, on="Country", how="left")

In [60]:
food_code["Country"] = food_code["Country"].replace({"Bahamas": "Bahamas, The", "Bolivia (Plurinational State of)": "Bolivia",
"China, Hong Kong SAR": "Hong Kong SAR, China", "China, Macao SAR": "Macao SAR, China", "Democratic Republic of the Congo": "Congo, Dem. Rep.",
"Congo": "Congo, Rep.", "Egypt": "Egypt, Arab Rep.", "Iran (Islamic Republic of)": "Iran, Islamic Rep.", "Republic of Korea": "Korea, Rep.",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "United States of America": "United States", "Venezuela (Bolivarian Republic of)": "Venezuela, RB"
})

In [61]:
food_code = pd.merge(food_code, country_lookup, on="Country", how="left")

In [65]:
food_code.columns

Index(['Country', 'Eggs', 'Fish, Seafood', 'Fruits - Excluding Wine', 'Meat',
       'Milk - Excluding Butter', 'Sugar & Sweeteners', 'Vegetables',
       'Country_Code_x', 'Country_Code_y'],
      dtype='object')

In [66]:
food_code["Country_Code"] = food_code["Country_Code_x"].fillna(food_code["Country_Code_y"])

In [67]:
food_code.drop(columns=["Country_Code_x", "Country_Code_y"], inplace=True)

In [68]:
food_code[food_code["Country_Code"].isnull()]["Country"]

32            China, Taiwan Province of
33                      China, mainland
41                        Côte d'Ivoire
57                               Gambia
84                           Kyrgyzstan
85     Lao People's Democratic Republic
102    Micronesia (Federated States of)
111        Netherlands (Kingdom of the)
130                 Republic of Moldova
134               Saint Kitts and Nevis
135                         Saint Lucia
136    Saint Vincent and the Grenadines
144                            Slovakia
162                             Türkiye
167         United Republic of Tanzania
174                               Yemen
Name: Country, dtype: object

In [69]:
gdp[gdp["Country"].str.contains("Taiwan", case=False, na=False)]

Empty DataFrame
Columns: [Country, Country_Code, GDP_per_Capita]
Index: []

In [70]:
gdp[gdp["Country"].str.contains("China", case=False, na=False)]

                  Country Country_Code  GDP_per_Capita
40                  China          CHN    12951.178240
96   Hong Kong SAR, China          HKG    50562.363314
146      Macao SAR, China          MAC    67216.363111

In [71]:
gdp[gdp["Country"].str.contains("Ivoire", case=False, na=False)]

          Country Country_Code  GDP_per_Capita
41  Cote d'Ivoire          CIV     2591.965905

In [72]:
gdp[gdp["Country"].str.contains("Gambia", case=False, na=False)]

        Country Country_Code  GDP_per_Capita
86  Gambia, The          GMB      883.024112

In [73]:
gdp[gdp["Country"].str.contains("Kyrgyz", case=False, na=False)]

             Country Country_Code  GDP_per_Capita
122  Kyrgyz Republic          KGZ     2138.222102

In [74]:
gdp[gdp["Country"].str.contains("Lao", case=False, na=False)]

     Country Country_Code  GDP_per_Capita
129  Lao PDR          LAO     2066.949798

In [75]:
gdp[gdp["Country"].str.contains("Micronesia", case=False, na=False)]

                  Country Country_Code  GDP_per_Capita
79  Micronesia, Fed. Sts.          FSM     3919.643079

In [76]:
gdp[gdp["Country"].str.contains("Netherlands", case=False, na=False)]

         Country Country_Code  GDP_per_Capita
176  Netherlands          NLD    63515.603078

In [77]:
gdp[gdp["Country"].str.contains("Moldova", case=False, na=False)]

     Country Country_Code  GDP_per_Capita
150  Moldova          MDA     6799.585946

In [78]:
gdp[gdp["Country"].str.contains("Saint", case=False, na=False)]

Empty DataFrame
Columns: [Country, Country_Code, GDP_per_Capita]
Index: []

In [79]:
gdp[gdp["Country"].str.contains("Slovak", case=False, na=False)]

             Country Country_Code  GDP_per_Capita
221  Slovak Republic          SVK    24614.873464

In [80]:
gdp[gdp["Country"].str.contains("Turk", case=False, na=False)]

                      Country Country_Code  GDP_per_Capita
228  Turks and Caicos Islands          TCA    35470.215161
235              Turkmenistan          TKM     6231.913238
244                   Turkiye          TUR    13375.094728

In [81]:
gdp[gdp["Country"].str.contains("Tanzania", case=False, na=False)]

      Country Country_Code  GDP_per_Capita
246  Tanzania          TZA     1224.002197

In [82]:
gdp[gdp["Country"].str.contains("Yemen", case=False, na=False)]

         Country Country_Code  GDP_per_Capita
262  Yemen, Rep.          YEM             NaN

In [83]:
food_code["Country"] = food_code["Country"].replace({
    "China, Taiwan Province of": "Taiwan, China",
    "China, mainland": "China",
    "Côte d'Ivoire": "Cote d'Ivoire",
    "Gambia": "Gambia, The",
    "Kyrgyzstan": "Kyrgyz Republic",
    "Lao People's Democratic Republic": "Lao PDR",
    "Micronesia (Federated States of)": "Micronesia, Fed. Sts.",
    "Netherlands (Kingdom of the)": "Netherlands",
    "Republic of Moldova": "Moldova",
    "Slovakia": "Slovak Republic",
    "Türkiye": "Turkiye",
    "United Republic of Tanzania": "Tanzania",
    "Yemen": "Yemen, Rep."
})

In [84]:
gdp[gdp["Country"].str.contains("Kitts", case=False, na=False)]

                 Country Country_Code  GDP_per_Capita
125  St. Kitts and Nevis          KNA    22576.924844

In [85]:
gdp[gdp["Country"].str.contains("Vincent", case=False, na=False)]

                            Country Country_Code  GDP_per_Capita
253  St. Vincent and the Grenadines          VCT    10582.365673

In [86]:
food_code = pd.merge(food_code.drop(columns="Country_Code"),
                     country_lookup,
                     on="Country",
                     how="left")

In [87]:
food_code[food_code["Country_Code"].isnull()]["Country"]

32                        Taiwan, China
134               Saint Kitts and Nevis
135                         Saint Lucia
136    Saint Vincent and the Grenadines
Name: Country, dtype: object

In [88]:
country_lookup[country_lookup["Country"].str.contains("Taiwan", case=False, na=False)]

Empty DataFrame
Columns: [Country, Country_Code]
Index: []

In [89]:
country_lookup[country_lookup["Country"].str.contains("Lucia", case=False, na=False)]

       Country Country_Code
133  St. Lucia          LCA

In [90]:
country_lookup[country_lookup["Country"].str.contains("Kitts", case=False, na=False)]

                 Country Country_Code
125  St. Kitts and Nevis          KNA

In [91]:
country_lookup[country_lookup["Country"].str.contains("Vincent", case=False, na=False)]

                            Country Country_Code
253  St. Vincent and the Grenadines          VCT

In [92]:
food_code["Country"] = food_code["Country"].replace({
    "Saint Lucia": "St. Lucia",
    "Saint Kitts and Nevis": "St. Kitts and Nevis",
    "Saint Vincent and the Grenadines": "St. Vincent and the Grenadines"
})

In [93]:
food_code = pd.merge(
    food_code.drop(columns="Country_Code"),
    country_lookup,
    on="Country",
    how="left"
)

In [94]:
food_code[food_code["Country_Code"].isnull()]["Country"]

32    Taiwan, China
Name: Country, dtype: object

In [95]:
food_code = food_code.drop(
    food_code[food_code["Country"] == "Taiwan, China"].index
)

In [96]:
food_code[food_code["Country_Code"].isnull()]["Country"]

Series([], Name: Country, dtype: object)

In [97]:
food_code.shape

(176, 9)

In [98]:
food_code.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\food_code.csv", index=False)

In [99]:
merged = pd.merge(food_code, gdp, on=["Country", "Country_Code"], how="left")

In [100]:
merged.shape

(176, 10)

In [101]:
merged.isnull().sum()

Country                    0
Eggs                       0
Fish, Seafood              0
Fruits - Excluding Wine    0
Meat                       0
Milk - Excluding Butter    0
Sugar & Sweeteners         0
Vegetables                 0
Country_Code               0
GDP_per_Capita             2
dtype: int64

In [102]:
merged[merged["GDP_per_Capita"].isnull()][["Country", "Country_Code"]]

                  Country Country_Code
152  Syrian Arab Republic          SYR
173           Yemen, Rep.          YEM

In [103]:
gdp[gdp["Country_Code"] == "SYR"]

                  Country Country_Code  GDP_per_Capita
227  Syrian Arab Republic          SYR             NaN

In [104]:
gdp[gdp["Country_Code"]=="YEM"]

         Country Country_Code  GDP_per_Capita
262  Yemen, Rep.          YEM             NaN

In [105]:
merged = pd.merge(
    merged,
    life,
    on=["Country", "Country_Code"],
    how="left"
)

In [106]:
merged.shape

(176, 11)

In [107]:
merged.isnull().sum()

Country                    0
Eggs                       0
Fish, Seafood              0
Fruits - Excluding Wine    0
Meat                       0
Milk - Excluding Butter    0
Sugar & Sweeteners         0
Vegetables                 0
Country_Code               0
GDP_per_Capita             2
Life_Expectancy            0
dtype: int64

In [108]:
merged = pd.merge(
    merged,
    diabetes,
    on=["Country", "Country_Code"],
    how="left"
)

In [109]:
merged.shape

(176, 12)

In [110]:
merged.isnull().sum()

Country                    0
Eggs                       0
Fish, Seafood              0
Fruits - Excluding Wine    0
Meat                       0
Milk - Excluding Butter    0
Sugar & Sweeteners         0
Vegetables                 0
Country_Code               0
GDP_per_Capita             2
Life_Expectancy            0
Diabetes_Prevalence        0
dtype: int64

In [111]:
merged = pd.merge(
    merged,
    obesity,
    on=["Country", "Country_Code"],
    how="left"
)

In [113]:
merged.shape

(176, 13)

In [114]:
merged.isnull().sum()

Country                     0
Eggs                        0
Fish, Seafood               0
Fruits - Excluding Wine     0
Meat                        0
Milk - Excluding Butter     0
Sugar & Sweeteners          0
Vegetables                  0
Country_Code                0
GDP_per_Capita              2
Life_Expectancy             0
Diabetes_Prevalence         0
Obesity                    26
dtype: int64

In [115]:
merged[merged["Obesity"].isnull()][["Country", "Country_Code"]]

                            Country Country_Code
10                     Bahamas, The          BHS
24                       Cabo Verde          CPV
30             Hong Kong SAR, China          HKG
31                 Macao SAR, China          MAC
35                      Congo, Rep.          COG
41                 Congo, Dem. Rep.          COD
46                 Egypt, Arab Rep.          EGY
54                 French Polynesia          PYF
56                      Gambia, The          GMB
72               Iran, Islamic Rep.          IRN
83                  Kyrgyz Republic          KGZ
84                          Lao PDR          LAO
101           Micronesia, Fed. Sts.          FSM
111                   New Caledonia          NCL
128                     Korea, Rep.          KOR
131              Russian Federation          RUS
133             St. Kitts and Nevis          KNA
134                       St. Lucia          LCA
135  St. Vincent and the Grenadines          VCT
143                 Slovak Republic          SVK
152            Syrian Arab Republic          SYR
155                     Timor-Leste          TLS
161                         Turkiye          TUR
171                   Venezuela, RB          VEN
172                        Viet Nam          VNM
173                     Yemen, Rep.          YEM

In [124]:
merged = pd.merge(merged, obesity[["Country_Code", "Obesity"]], on="Country_Code", how="left")

In [125]:
merged.isnull().sum()

Country                     0
Eggs                        0
Fish, Seafood               0
Fruits - Excluding Wine     0
Meat                        0
Milk - Excluding Butter     0
Sugar & Sweeteners          0
Vegetables                  0
Country_Code                0
GDP_per_Capita              2
Life_Expectancy             0
Diabetes_Prevalence         0
Obesity_x                  26
Obesity_y                   4
dtype: int64

In [126]:
merged.drop(columns="Obesity_x", inplace=True)

In [127]:
merged.rename(columns={"Obesity_y": "Obesity"}, inplace=True)

In [128]:
merged.isnull().sum()

Country                    0
Eggs                       0
Fish, Seafood              0
Fruits - Excluding Wine    0
Meat                       0
Milk - Excluding Butter    0
Sugar & Sweeteners         0
Vegetables                 0
Country_Code               0
GDP_per_Capita             2
Life_Expectancy            0
Diabetes_Prevalence        0
Obesity                    4
dtype: int64

In [134]:
merged.to_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\diet-health-analysis project\data\processed\merged_data.csv", index=False)